// Generated by gencpp from file assignments/CheckJointState.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_CHECKJOINTSTATE_H
#define ASSIGNMENTS_MESSAGE_CHECKJOINTSTATE_H

#include <ros/service_traits.h>


#include <assignments/CheckJointStateRequest.h>
#include <assignments/CheckJointStateResponse.h>


namespace assignments
{

struct CheckJointState
{

typedef CheckJointStateRequest Request;
typedef CheckJointStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckJointState
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::CheckJointState > {
  static const char* value()
  {
    return "92da1e14e4cd448e7306767001ef56ff";
  }

  static const char* value(const ::assignments::CheckJointState&) { return value(); }
};

template<>
struct DataType< ::assignments::CheckJointState > {
  static const char* value()
  {
    return "assignments/CheckJointState";
  }

  static const char* value(const ::assignments::CheckJointState&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::CheckJointStateRequest> should match
// service_traits::MD5Sum< ::assignments::CheckJointState >
template<>
struct MD5Sum< ::assignments::CheckJointStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::CheckJointState >::value();
  }
  static const char* value(const ::assignments::CheckJointStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::CheckJointStateRequest> should match
// service_traits::DataType< ::assignments::CheckJointState >
template<>
struct DataType< ::assignments::CheckJointStateRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::CheckJointState >::value();
  }
  static const char* value(const ::assignments::CheckJointStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::CheckJointStateResponse> should match
// service_traits::MD5Sum< ::assignments::CheckJointState >
template<>
struct MD5Sum< ::assignments::CheckJointStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::CheckJointState >::value();
  }
  static const char* value(const ::assignments::CheckJointStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::CheckJointStateResponse> should match
// service_traits::DataType< ::assignments::CheckJointState >
template<>
struct DataType< ::assignments::CheckJointStateResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::CheckJointState >::value();
  }
  static const char* value(const ::assignments::CheckJointStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_CHECKJOINTSTATE_H
