// Generated by gencpp from file assignments/CheckJointStateRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_CHECKJOINTSTATEREQUEST_H
#define ASSIGNMENTS_MESSAGE_CHECKJOINTSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct CheckJointStateRequest_
{
  typedef CheckJointStateRequest_<ContainerAllocator> Type;

  CheckJointStateRequest_()
    : positions()
    , velocities()
    , efforts()  {
    }
  CheckJointStateRequest_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , velocities(_alloc)
    , efforts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _positions_type;
  _positions_type positions;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocities_type;
  _velocities_type velocities;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _efforts_type;
  _efforts_type efforts;





  typedef boost::shared_ptr< ::assignments::CheckJointStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::CheckJointStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckJointStateRequest_

typedef ::assignments::CheckJointStateRequest_<std::allocator<void> > CheckJointStateRequest;

typedef boost::shared_ptr< ::assignments::CheckJointStateRequest > CheckJointStateRequestPtr;
typedef boost::shared_ptr< ::assignments::CheckJointStateRequest const> CheckJointStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::CheckJointStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::CheckJointStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::CheckJointStateRequest_<ContainerAllocator1> & lhs, const ::assignments::CheckJointStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions &&
    lhs.velocities == rhs.velocities &&
    lhs.efforts == rhs.efforts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::CheckJointStateRequest_<ContainerAllocator1> & lhs, const ::assignments::CheckJointStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::CheckJointStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::CheckJointStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::CheckJointStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9ca0af36daadfa3b4628ccba7ca6819";
  }

  static const char* value(const ::assignments::CheckJointStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9ca0af36daadfa3ULL;
  static const uint64_t static_value2 = 0xb4628ccba7ca6819ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/CheckJointStateRequest";
  }

  static const char* value(const ::assignments::CheckJointStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: a JointState-like structure\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] efforts\n"
"\n"
;
  }

  static const char* value(const ::assignments::CheckJointStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.velocities);
      stream.next(m.efforts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckJointStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::CheckJointStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::CheckJointStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
    s << indent << "efforts[]" << std::endl;
    for (size_t i = 0; i < v.efforts.size(); ++i)
    {
      s << indent << "  efforts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.efforts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_CHECKJOINTSTATEREQUEST_H
