// Generated by gencpp from file assignments/CheckJointStateResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_CHECKJOINTSTATERESPONSE_H
#define ASSIGNMENTS_MESSAGE_CHECKJOINTSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct CheckJointStateResponse_
{
  typedef CheckJointStateResponse_<ContainerAllocator> Type;

  CheckJointStateResponse_()
    : success(false)  {
    }
  CheckJointStateResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignments::CheckJointStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::CheckJointStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckJointStateResponse_

typedef ::assignments::CheckJointStateResponse_<std::allocator<void> > CheckJointStateResponse;

typedef boost::shared_ptr< ::assignments::CheckJointStateResponse > CheckJointStateResponsePtr;
typedef boost::shared_ptr< ::assignments::CheckJointStateResponse const> CheckJointStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::CheckJointStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::CheckJointStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::CheckJointStateResponse_<ContainerAllocator1> & lhs, const ::assignments::CheckJointStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::CheckJointStateResponse_<ContainerAllocator1> & lhs, const ::assignments::CheckJointStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::CheckJointStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::CheckJointStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::CheckJointStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::assignments::CheckJointStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/CheckJointStateResponse";
  }

  static const char* value(const ::assignments::CheckJointStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: boolean indicating if the dimensions match\n"
"bool success\n"
;
  }

  static const char* value(const ::assignments::CheckJointStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckJointStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::CheckJointStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::CheckJointStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_CHECKJOINTSTATERESPONSE_H
