// Generated by gencpp from file assignments/InterpreterCommandRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_INTERPRETERCOMMANDREQUEST_H
#define ASSIGNMENTS_MESSAGE_INTERPRETERCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct InterpreterCommandRequest_
{
  typedef InterpreterCommandRequest_<ContainerAllocator> Type;

  InterpreterCommandRequest_()
    : user_command()
    , current_step()  {
    }
  InterpreterCommandRequest_(const ContainerAllocator& _alloc)
    : user_command(_alloc)
    , current_step(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_command_type;
  _user_command_type user_command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _current_step_type;
  _current_step_type current_step;





  typedef boost::shared_ptr< ::assignments::InterpreterCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::InterpreterCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InterpreterCommandRequest_

typedef ::assignments::InterpreterCommandRequest_<std::allocator<void> > InterpreterCommandRequest;

typedef boost::shared_ptr< ::assignments::InterpreterCommandRequest > InterpreterCommandRequestPtr;
typedef boost::shared_ptr< ::assignments::InterpreterCommandRequest const> InterpreterCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::InterpreterCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::InterpreterCommandRequest_<ContainerAllocator1> & lhs, const ::assignments::InterpreterCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user_command == rhs.user_command &&
    lhs.current_step == rhs.current_step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::InterpreterCommandRequest_<ContainerAllocator1> & lhs, const ::assignments::InterpreterCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::InterpreterCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::InterpreterCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::InterpreterCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6680fa6dc6ba89d32386ab909f49a08";
  }

  static const char* value(const ::assignments::InterpreterCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6680fa6dc6ba89dULL;
  static const uint64_t static_value2 = 0x32386ab909f49a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/InterpreterCommandRequest";
  }

  static const char* value(const ::assignments::InterpreterCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string user_command\n"
"string current_step\n"
"\n"
;
  }

  static const char* value(const ::assignments::InterpreterCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_command);
      stream.next(m.current_step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterpreterCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::InterpreterCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::InterpreterCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "user_command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user_command);
    s << indent << "current_step: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.current_step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_INTERPRETERCOMMANDREQUEST_H
