// Generated by gencpp from file assignments/InterpreterCommand.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_INTERPRETERCOMMAND_H
#define ASSIGNMENTS_MESSAGE_INTERPRETERCOMMAND_H

#include <ros/service_traits.h>


#include <assignments/InterpreterCommandRequest.h>
#include <assignments/InterpreterCommandResponse.h>


namespace assignments
{

struct InterpreterCommand
{

typedef InterpreterCommandRequest Request;
typedef InterpreterCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InterpreterCommand
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::InterpreterCommand > {
  static const char* value()
  {
    return "233406fee41744d870c89e8f3e025de8";
  }

  static const char* value(const ::assignments::InterpreterCommand&) { return value(); }
};

template<>
struct DataType< ::assignments::InterpreterCommand > {
  static const char* value()
  {
    return "assignments/InterpreterCommand";
  }

  static const char* value(const ::assignments::InterpreterCommand&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::InterpreterCommandRequest> should match
// service_traits::MD5Sum< ::assignments::InterpreterCommand >
template<>
struct MD5Sum< ::assignments::InterpreterCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::InterpreterCommand >::value();
  }
  static const char* value(const ::assignments::InterpreterCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::InterpreterCommandRequest> should match
// service_traits::DataType< ::assignments::InterpreterCommand >
template<>
struct DataType< ::assignments::InterpreterCommandRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::InterpreterCommand >::value();
  }
  static const char* value(const ::assignments::InterpreterCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::InterpreterCommandResponse> should match
// service_traits::MD5Sum< ::assignments::InterpreterCommand >
template<>
struct MD5Sum< ::assignments::InterpreterCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::InterpreterCommand >::value();
  }
  static const char* value(const ::assignments::InterpreterCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::InterpreterCommandResponse> should match
// service_traits::DataType< ::assignments::InterpreterCommand >
template<>
struct DataType< ::assignments::InterpreterCommandResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::InterpreterCommand >::value();
  }
  static const char* value(const ::assignments::InterpreterCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_INTERPRETERCOMMAND_H
