// Generated by gencpp from file assignments/MissionStatus.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_MISSIONSTATUS_H
#define ASSIGNMENTS_MESSAGE_MISSIONSTATUS_H

#include <ros/service_traits.h>


#include <assignments/MissionStatusRequest.h>
#include <assignments/MissionStatusResponse.h>


namespace assignments
{

struct MissionStatus
{

typedef MissionStatusRequest Request;
typedef MissionStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionStatus
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::MissionStatus > {
  static const char* value()
  {
    return "8473414d924f983938aed34e90fbc692";
  }

  static const char* value(const ::assignments::MissionStatus&) { return value(); }
};

template<>
struct DataType< ::assignments::MissionStatus > {
  static const char* value()
  {
    return "assignments/MissionStatus";
  }

  static const char* value(const ::assignments::MissionStatus&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::MissionStatusRequest> should match
// service_traits::MD5Sum< ::assignments::MissionStatus >
template<>
struct MD5Sum< ::assignments::MissionStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::MissionStatus >::value();
  }
  static const char* value(const ::assignments::MissionStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::MissionStatusRequest> should match
// service_traits::DataType< ::assignments::MissionStatus >
template<>
struct DataType< ::assignments::MissionStatusRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::MissionStatus >::value();
  }
  static const char* value(const ::assignments::MissionStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::MissionStatusResponse> should match
// service_traits::MD5Sum< ::assignments::MissionStatus >
template<>
struct MD5Sum< ::assignments::MissionStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::MissionStatus >::value();
  }
  static const char* value(const ::assignments::MissionStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::MissionStatusResponse> should match
// service_traits::DataType< ::assignments::MissionStatus >
template<>
struct DataType< ::assignments::MissionStatusResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::MissionStatus >::value();
  }
  static const char* value(const ::assignments::MissionStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_MISSIONSTATUS_H
