// Generated by gencpp from file assignments/mission_statusRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_MISSION_STATUSREQUEST_H
#define ASSIGNMENTS_MESSAGE_MISSION_STATUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct mission_statusRequest_
{
  typedef mission_statusRequest_<ContainerAllocator> Type;

  mission_statusRequest_()
    : mission_id()
    , success(false)  {
    }
  mission_statusRequest_(const ContainerAllocator& _alloc)
    : mission_id(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mission_id_type;
  _mission_id_type mission_id;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignments::mission_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::mission_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mission_statusRequest_

typedef ::assignments::mission_statusRequest_<std::allocator<void> > mission_statusRequest;

typedef boost::shared_ptr< ::assignments::mission_statusRequest > mission_statusRequestPtr;
typedef boost::shared_ptr< ::assignments::mission_statusRequest const> mission_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::mission_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::mission_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::mission_statusRequest_<ContainerAllocator1> & lhs, const ::assignments::mission_statusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mission_id == rhs.mission_id &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::mission_statusRequest_<ContainerAllocator1> & lhs, const ::assignments::mission_statusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::mission_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::mission_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::mission_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::mission_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::mission_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::mission_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::mission_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c20f36d179e811bb0acd97de1ab9246a";
  }

  static const char* value(const ::assignments::mission_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc20f36d179e811bbULL;
  static const uint64_t static_value2 = 0x0acd97de1ab9246aULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::mission_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/mission_statusRequest";
  }

  static const char* value(const ::assignments::mission_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::mission_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: Information about the status of the mission.\n"
"string mission_id\n"
"bool success  # If the mission is successfully completed.\n"
"\n"
;
  }

  static const char* value(const ::assignments::mission_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::mission_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_id);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::mission_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::mission_statusRequest_<ContainerAllocator>& v)
  {
    s << indent << "mission_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mission_id);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_MISSION_STATUSREQUEST_H
