// Generated by gencpp from file assignments/MissionStatusRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_MISSIONSTATUSREQUEST_H
#define ASSIGNMENTS_MESSAGE_MISSIONSTATUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct MissionStatusRequest_
{
  typedef MissionStatusRequest_<ContainerAllocator> Type;

  MissionStatusRequest_()
    : mission_id()
    , success(false)  {
    }
  MissionStatusRequest_(const ContainerAllocator& _alloc)
    : mission_id(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mission_id_type;
  _mission_id_type mission_id;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignments::MissionStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::MissionStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MissionStatusRequest_

typedef ::assignments::MissionStatusRequest_<std::allocator<void> > MissionStatusRequest;

typedef boost::shared_ptr< ::assignments::MissionStatusRequest > MissionStatusRequestPtr;
typedef boost::shared_ptr< ::assignments::MissionStatusRequest const> MissionStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::MissionStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::MissionStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::MissionStatusRequest_<ContainerAllocator1> & lhs, const ::assignments::MissionStatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mission_id == rhs.mission_id &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::MissionStatusRequest_<ContainerAllocator1> & lhs, const ::assignments::MissionStatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::MissionStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::MissionStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::MissionStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::MissionStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::MissionStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::MissionStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::MissionStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c20f36d179e811bb0acd97de1ab9246a";
  }

  static const char* value(const ::assignments::MissionStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc20f36d179e811bbULL;
  static const uint64_t static_value2 = 0x0acd97de1ab9246aULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::MissionStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/MissionStatusRequest";
  }

  static const char* value(const ::assignments::MissionStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::MissionStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: Information about the status of the mission.\n"
"string mission_id\n"
"bool success  # If the mission is successfully completed.\n"
"\n"
;
  }

  static const char* value(const ::assignments::MissionStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::MissionStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_id);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::MissionStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::MissionStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "mission_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mission_id);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_MISSIONSTATUSREQUEST_H
