// Generated by gencpp from file assignments/mission_status.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_MISSION_STATUS_H
#define ASSIGNMENTS_MESSAGE_MISSION_STATUS_H

#include <ros/service_traits.h>


#include <assignments/mission_statusRequest.h>
#include <assignments/mission_statusResponse.h>


namespace assignments
{

struct mission_status
{

typedef mission_statusRequest Request;
typedef mission_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mission_status
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::mission_status > {
  static const char* value()
  {
    return "8473414d924f983938aed34e90fbc692";
  }

  static const char* value(const ::assignments::mission_status&) { return value(); }
};

template<>
struct DataType< ::assignments::mission_status > {
  static const char* value()
  {
    return "assignments/mission_status";
  }

  static const char* value(const ::assignments::mission_status&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::mission_statusRequest> should match
// service_traits::MD5Sum< ::assignments::mission_status >
template<>
struct MD5Sum< ::assignments::mission_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::mission_status >::value();
  }
  static const char* value(const ::assignments::mission_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::mission_statusRequest> should match
// service_traits::DataType< ::assignments::mission_status >
template<>
struct DataType< ::assignments::mission_statusRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::mission_status >::value();
  }
  static const char* value(const ::assignments::mission_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::mission_statusResponse> should match
// service_traits::MD5Sum< ::assignments::mission_status >
template<>
struct MD5Sum< ::assignments::mission_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::mission_status >::value();
  }
  static const char* value(const ::assignments::mission_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::mission_statusResponse> should match
// service_traits::DataType< ::assignments::mission_status >
template<>
struct DataType< ::assignments::mission_statusResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::mission_status >::value();
  }
  static const char* value(const ::assignments::mission_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_MISSION_STATUS_H
