// Generated by gencpp from file assignments/NotificationsRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_NOTIFICATIONSREQUEST_H
#define ASSIGNMENTS_MESSAGE_NOTIFICATIONSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct NotificationsRequest_
{
  typedef NotificationsRequest_<ContainerAllocator> Type;

  NotificationsRequest_()
    : plate_name()
    , table_number()  {
    }
  NotificationsRequest_(const ContainerAllocator& _alloc)
    : plate_name(_alloc)
    , table_number(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _plate_name_type;
  _plate_name_type plate_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _table_number_type;
  _table_number_type table_number;





  typedef boost::shared_ptr< ::assignments::NotificationsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::NotificationsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NotificationsRequest_

typedef ::assignments::NotificationsRequest_<std::allocator<void> > NotificationsRequest;

typedef boost::shared_ptr< ::assignments::NotificationsRequest > NotificationsRequestPtr;
typedef boost::shared_ptr< ::assignments::NotificationsRequest const> NotificationsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::NotificationsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::NotificationsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::NotificationsRequest_<ContainerAllocator1> & lhs, const ::assignments::NotificationsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plate_name == rhs.plate_name &&
    lhs.table_number == rhs.table_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::NotificationsRequest_<ContainerAllocator1> & lhs, const ::assignments::NotificationsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::NotificationsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::NotificationsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::NotificationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::NotificationsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::NotificationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::NotificationsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::NotificationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c21072be71a7505b708c3fb22486d4d5";
  }

  static const char* value(const ::assignments::NotificationsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc21072be71a7505bULL;
  static const uint64_t static_value2 = 0x708c3fb22486d4d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::NotificationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/NotificationsRequest";
  }

  static const char* value(const ::assignments::NotificationsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::NotificationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: The name of the plate that was incorrectly delivered, and the table information.\n"
"string plate_name\n"
"string table_number  # The table where the wrong plate was delivered.\n"
"\n"
;
  }

  static const char* value(const ::assignments::NotificationsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::NotificationsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plate_name);
      stream.next(m.table_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NotificationsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::NotificationsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::NotificationsRequest_<ContainerAllocator>& v)
  {
    s << indent << "plate_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.plate_name);
    s << indent << "table_number: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.table_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_NOTIFICATIONSREQUEST_H
