// Generated by gencpp from file assignments/notifications.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_NOTIFICATIONS_H
#define ASSIGNMENTS_MESSAGE_NOTIFICATIONS_H

#include <ros/service_traits.h>


#include <assignments/notificationsRequest.h>
#include <assignments/notificationsResponse.h>


namespace assignments
{

struct notifications
{

typedef notificationsRequest Request;
typedef notificationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct notifications
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::notifications > {
  static const char* value()
  {
    return "31471cbc5866c6110d0f43de5ac7621e";
  }

  static const char* value(const ::assignments::notifications&) { return value(); }
};

template<>
struct DataType< ::assignments::notifications > {
  static const char* value()
  {
    return "assignments/notifications";
  }

  static const char* value(const ::assignments::notifications&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::notificationsRequest> should match
// service_traits::MD5Sum< ::assignments::notifications >
template<>
struct MD5Sum< ::assignments::notificationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::notifications >::value();
  }
  static const char* value(const ::assignments::notificationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::notificationsRequest> should match
// service_traits::DataType< ::assignments::notifications >
template<>
struct DataType< ::assignments::notificationsRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::notifications >::value();
  }
  static const char* value(const ::assignments::notificationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::notificationsResponse> should match
// service_traits::MD5Sum< ::assignments::notifications >
template<>
struct MD5Sum< ::assignments::notificationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::notifications >::value();
  }
  static const char* value(const ::assignments::notificationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::notificationsResponse> should match
// service_traits::DataType< ::assignments::notifications >
template<>
struct DataType< ::assignments::notificationsResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::notifications >::value();
  }
  static const char* value(const ::assignments::notificationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_NOTIFICATIONS_H
