// Generated by gencpp from file assignments/notificationsResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_NOTIFICATIONSRESPONSE_H
#define ASSIGNMENTS_MESSAGE_NOTIFICATIONSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct notificationsResponse_
{
  typedef notificationsResponse_<ContainerAllocator> Type;

  notificationsResponse_()
    : success(false)
    , message()  {
    }
  notificationsResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::assignments::notificationsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::notificationsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct notificationsResponse_

typedef ::assignments::notificationsResponse_<std::allocator<void> > notificationsResponse;

typedef boost::shared_ptr< ::assignments::notificationsResponse > notificationsResponsePtr;
typedef boost::shared_ptr< ::assignments::notificationsResponse const> notificationsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::notificationsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::notificationsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::notificationsResponse_<ContainerAllocator1> & lhs, const ::assignments::notificationsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::notificationsResponse_<ContainerAllocator1> & lhs, const ::assignments::notificationsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::notificationsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::notificationsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::notificationsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::notificationsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::notificationsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::notificationsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::notificationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::assignments::notificationsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::notificationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/notificationsResponse";
  }

  static const char* value(const ::assignments::notificationsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::notificationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: Confirmation if the notification was successfully sent.\n"
"bool success\n"
"string message  # A message confirming the notification, e.g., \"Notification sent to staff.\"\n"
;
  }

  static const char* value(const ::assignments::notificationsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::notificationsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct notificationsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::notificationsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::notificationsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_NOTIFICATIONSRESPONSE_H
