// Generated by gencpp from file assignments/ResolveConflictRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_RESOLVECONFLICTREQUEST_H
#define ASSIGNMENTS_MESSAGE_RESOLVECONFLICTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct ResolveConflictRequest_
{
  typedef ResolveConflictRequest_<ContainerAllocator> Type;

  ResolveConflictRequest_()
    : user_command()
    , planned_action()  {
    }
  ResolveConflictRequest_(const ContainerAllocator& _alloc)
    : user_command(_alloc)
    , planned_action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_command_type;
  _user_command_type user_command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _planned_action_type;
  _planned_action_type planned_action;





  typedef boost::shared_ptr< ::assignments::ResolveConflictRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::ResolveConflictRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResolveConflictRequest_

typedef ::assignments::ResolveConflictRequest_<std::allocator<void> > ResolveConflictRequest;

typedef boost::shared_ptr< ::assignments::ResolveConflictRequest > ResolveConflictRequestPtr;
typedef boost::shared_ptr< ::assignments::ResolveConflictRequest const> ResolveConflictRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::ResolveConflictRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::ResolveConflictRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::ResolveConflictRequest_<ContainerAllocator1> & lhs, const ::assignments::ResolveConflictRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user_command == rhs.user_command &&
    lhs.planned_action == rhs.planned_action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::ResolveConflictRequest_<ContainerAllocator1> & lhs, const ::assignments::ResolveConflictRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::ResolveConflictRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::ResolveConflictRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::ResolveConflictRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c8f9cb37e5eafaeb55b83c804bdfcc0";
  }

  static const char* value(const ::assignments::ResolveConflictRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c8f9cb37e5eafaeULL;
  static const uint64_t static_value2 = 0xb55b83c804bdfcc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/ResolveConflictRequest";
  }

  static const char* value(const ::assignments::ResolveConflictRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string user_command\n"
"string planned_action\n"
"\n"
;
  }

  static const char* value(const ::assignments::ResolveConflictRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_command);
      stream.next(m.planned_action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResolveConflictRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::ResolveConflictRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::ResolveConflictRequest_<ContainerAllocator>& v)
  {
    s << indent << "user_command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user_command);
    s << indent << "planned_action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.planned_action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_RESOLVECONFLICTREQUEST_H
