// Generated by gencpp from file assignments/ResolveConflictResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_RESOLVECONFLICTRESPONSE_H
#define ASSIGNMENTS_MESSAGE_RESOLVECONFLICTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct ResolveConflictResponse_
{
  typedef ResolveConflictResponse_<ContainerAllocator> Type;

  ResolveConflictResponse_()
    : success(false)
    , action_taken()  {
    }
  ResolveConflictResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , action_taken(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_taken_type;
  _action_taken_type action_taken;





  typedef boost::shared_ptr< ::assignments::ResolveConflictResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::ResolveConflictResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResolveConflictResponse_

typedef ::assignments::ResolveConflictResponse_<std::allocator<void> > ResolveConflictResponse;

typedef boost::shared_ptr< ::assignments::ResolveConflictResponse > ResolveConflictResponsePtr;
typedef boost::shared_ptr< ::assignments::ResolveConflictResponse const> ResolveConflictResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::ResolveConflictResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::ResolveConflictResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::ResolveConflictResponse_<ContainerAllocator1> & lhs, const ::assignments::ResolveConflictResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.action_taken == rhs.action_taken;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::ResolveConflictResponse_<ContainerAllocator1> & lhs, const ::assignments::ResolveConflictResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::ResolveConflictResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::ResolveConflictResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::ResolveConflictResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7cb82da9de0c8ef9eaae41a43f71655";
  }

  static const char* value(const ::assignments::ResolveConflictResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7cb82da9de0c8efULL;
  static const uint64_t static_value2 = 0x9eaae41a43f71655ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/ResolveConflictResponse";
  }

  static const char* value(const ::assignments::ResolveConflictResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success\n"
"string action_taken\n"
;
  }

  static const char* value(const ::assignments::ResolveConflictResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.action_taken);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResolveConflictResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::ResolveConflictResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::ResolveConflictResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "action_taken: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action_taken);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_RESOLVECONFLICTRESPONSE_H
