// Generated by gencpp from file assignments/ResolveConflict.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_RESOLVECONFLICT_H
#define ASSIGNMENTS_MESSAGE_RESOLVECONFLICT_H

#include <ros/service_traits.h>


#include <assignments/ResolveConflictRequest.h>
#include <assignments/ResolveConflictResponse.h>


namespace assignments
{

struct ResolveConflict
{

typedef ResolveConflictRequest Request;
typedef ResolveConflictResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResolveConflict
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::ResolveConflict > {
  static const char* value()
  {
    return "46e09040b26dd91cb6b1cac06fbcae3b";
  }

  static const char* value(const ::assignments::ResolveConflict&) { return value(); }
};

template<>
struct DataType< ::assignments::ResolveConflict > {
  static const char* value()
  {
    return "assignments/ResolveConflict";
  }

  static const char* value(const ::assignments::ResolveConflict&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::ResolveConflictRequest> should match
// service_traits::MD5Sum< ::assignments::ResolveConflict >
template<>
struct MD5Sum< ::assignments::ResolveConflictRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::ResolveConflict >::value();
  }
  static const char* value(const ::assignments::ResolveConflictRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::ResolveConflictRequest> should match
// service_traits::DataType< ::assignments::ResolveConflict >
template<>
struct DataType< ::assignments::ResolveConflictRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::ResolveConflict >::value();
  }
  static const char* value(const ::assignments::ResolveConflictRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::ResolveConflictResponse> should match
// service_traits::MD5Sum< ::assignments::ResolveConflict >
template<>
struct MD5Sum< ::assignments::ResolveConflictResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::ResolveConflict >::value();
  }
  static const char* value(const ::assignments::ResolveConflictResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::ResolveConflictResponse> should match
// service_traits::DataType< ::assignments::ResolveConflict >
template<>
struct DataType< ::assignments::ResolveConflictResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::ResolveConflict >::value();
  }
  static const char* value(const ::assignments::ResolveConflictResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_RESOLVECONFLICT_H
