// Generated by gencpp from file assignments/RiskEvaluation.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_RISKEVALUATION_H
#define ASSIGNMENTS_MESSAGE_RISKEVALUATION_H

#include <ros/service_traits.h>


#include <assignments/RiskEvaluationRequest.h>
#include <assignments/RiskEvaluationResponse.h>


namespace assignments
{

struct RiskEvaluation
{

typedef RiskEvaluationRequest Request;
typedef RiskEvaluationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RiskEvaluation
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::RiskEvaluation > {
  static const char* value()
  {
    return "2ad8d9fb9c81a63740c12dbd83c357d9";
  }

  static const char* value(const ::assignments::RiskEvaluation&) { return value(); }
};

template<>
struct DataType< ::assignments::RiskEvaluation > {
  static const char* value()
  {
    return "assignments/RiskEvaluation";
  }

  static const char* value(const ::assignments::RiskEvaluation&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::RiskEvaluationRequest> should match
// service_traits::MD5Sum< ::assignments::RiskEvaluation >
template<>
struct MD5Sum< ::assignments::RiskEvaluationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::RiskEvaluation >::value();
  }
  static const char* value(const ::assignments::RiskEvaluationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::RiskEvaluationRequest> should match
// service_traits::DataType< ::assignments::RiskEvaluation >
template<>
struct DataType< ::assignments::RiskEvaluationRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::RiskEvaluation >::value();
  }
  static const char* value(const ::assignments::RiskEvaluationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::RiskEvaluationResponse> should match
// service_traits::MD5Sum< ::assignments::RiskEvaluation >
template<>
struct MD5Sum< ::assignments::RiskEvaluationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::RiskEvaluation >::value();
  }
  static const char* value(const ::assignments::RiskEvaluationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::RiskEvaluationResponse> should match
// service_traits::DataType< ::assignments::RiskEvaluation >
template<>
struct DataType< ::assignments::RiskEvaluationResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::RiskEvaluation >::value();
  }
  static const char* value(const ::assignments::RiskEvaluationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_RISKEVALUATION_H
