// Generated by gencpp from file assignments/victim_report.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_VICTIM_REPORT_H
#define ASSIGNMENTS_MESSAGE_VICTIM_REPORT_H

#include <ros/service_traits.h>


#include <assignments/victim_reportRequest.h>
#include <assignments/victim_reportResponse.h>


namespace assignments
{

struct victim_report
{

typedef victim_reportRequest Request;
typedef victim_reportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct victim_report
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::victim_report > {
  static const char* value()
  {
    return "5842e2c98f4b10149f7dbf8a9ec4edf6";
  }

  static const char* value(const ::assignments::victim_report&) { return value(); }
};

template<>
struct DataType< ::assignments::victim_report > {
  static const char* value()
  {
    return "assignments/victim_report";
  }

  static const char* value(const ::assignments::victim_report&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::victim_reportRequest> should match
// service_traits::MD5Sum< ::assignments::victim_report >
template<>
struct MD5Sum< ::assignments::victim_reportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::victim_report >::value();
  }
  static const char* value(const ::assignments::victim_reportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::victim_reportRequest> should match
// service_traits::DataType< ::assignments::victim_report >
template<>
struct DataType< ::assignments::victim_reportRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::victim_report >::value();
  }
  static const char* value(const ::assignments::victim_reportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::victim_reportResponse> should match
// service_traits::MD5Sum< ::assignments::victim_report >
template<>
struct MD5Sum< ::assignments::victim_reportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::victim_report >::value();
  }
  static const char* value(const ::assignments::victim_reportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::victim_reportResponse> should match
// service_traits::DataType< ::assignments::victim_report >
template<>
struct DataType< ::assignments::victim_reportResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::victim_report >::value();
  }
  static const char* value(const ::assignments::victim_reportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_VICTIM_REPORT_H
