// Generated by gencpp from file assignments/VictimReport.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_VICTIMREPORT_H
#define ASSIGNMENTS_MESSAGE_VICTIMREPORT_H

#include <ros/service_traits.h>


#include <assignments/VictimReportRequest.h>
#include <assignments/VictimReportResponse.h>


namespace assignments
{

struct VictimReport
{

typedef VictimReportRequest Request;
typedef VictimReportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VictimReport
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::VictimReport > {
  static const char* value()
  {
    return "5842e2c98f4b10149f7dbf8a9ec4edf6";
  }

  static const char* value(const ::assignments::VictimReport&) { return value(); }
};

template<>
struct DataType< ::assignments::VictimReport > {
  static const char* value()
  {
    return "assignments/VictimReport";
  }

  static const char* value(const ::assignments::VictimReport&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::VictimReportRequest> should match
// service_traits::MD5Sum< ::assignments::VictimReport >
template<>
struct MD5Sum< ::assignments::VictimReportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::VictimReport >::value();
  }
  static const char* value(const ::assignments::VictimReportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::VictimReportRequest> should match
// service_traits::DataType< ::assignments::VictimReport >
template<>
struct DataType< ::assignments::VictimReportRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::VictimReport >::value();
  }
  static const char* value(const ::assignments::VictimReportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::VictimReportResponse> should match
// service_traits::MD5Sum< ::assignments::VictimReport >
template<>
struct MD5Sum< ::assignments::VictimReportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::VictimReport >::value();
  }
  static const char* value(const ::assignments::VictimReportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::VictimReportResponse> should match
// service_traits::DataType< ::assignments::VictimReport >
template<>
struct DataType< ::assignments::VictimReportResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::VictimReport >::value();
  }
  static const char* value(const ::assignments::VictimReportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_VICTIMREPORT_H
