// Generated by gencpp from file assignments/victim_reportRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_VICTIM_REPORTREQUEST_H
#define ASSIGNMENTS_MESSAGE_VICTIM_REPORTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct victim_reportRequest_
{
  typedef victim_reportRequest_<ContainerAllocator> Type;

  victim_reportRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , victim_status()  {
    }
  victim_reportRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , victim_status(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _victim_status_type;
  _victim_status_type victim_status;





  typedef boost::shared_ptr< ::assignments::victim_reportRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::victim_reportRequest_<ContainerAllocator> const> ConstPtr;

}; // struct victim_reportRequest_

typedef ::assignments::victim_reportRequest_<std::allocator<void> > victim_reportRequest;

typedef boost::shared_ptr< ::assignments::victim_reportRequest > victim_reportRequestPtr;
typedef boost::shared_ptr< ::assignments::victim_reportRequest const> victim_reportRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::victim_reportRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::victim_reportRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::victim_reportRequest_<ContainerAllocator1> & lhs, const ::assignments::victim_reportRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.victim_status == rhs.victim_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::victim_reportRequest_<ContainerAllocator1> & lhs, const ::assignments::victim_reportRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::victim_reportRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::victim_reportRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::victim_reportRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::victim_reportRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::victim_reportRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::victim_reportRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::victim_reportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b9885cf44444112fcf5513fbb6b1f11";
  }

  static const char* value(const ::assignments::victim_reportRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b9885cf44444112ULL;
  static const uint64_t static_value2 = 0xfcf5513fbb6b1f11ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::victim_reportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/victim_reportRequest";
  }

  static const char* value(const ::assignments::victim_reportRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::victim_reportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: The location of the detected victim (position in the environment).\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"string victim_status  # E.g., \"conscious\", \"unconscious\", \"critical\", etc.\n"
"\n"
;
  }

  static const char* value(const ::assignments::victim_reportRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::victim_reportRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.victim_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct victim_reportRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::victim_reportRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::victim_reportRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "victim_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.victim_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_VICTIM_REPORTREQUEST_H
